### PR TITLE
Adding csv file for OT+IT cabling map

### PR DESCRIPTION
**Pull request by adewit**
This adds the data needed to produce a cabling map for both IT and OT

### CODE REVIEW

**Comment by tvami** [comment]
+alca

**Comment by mmusich** [comment]
> DQMHistoTests: Total failures: 23351

@smuzaffar there is something broken with the bot comparison, this PR is showing a huge list of difference, while it is not changing anything related to relvals, just adding a new file.

**Comment by smuzaffar** [comment]
this is because it rebuilt the externals which has already been merged on top of `CMSSW_12_2_X_2021-12-01-2300` IB e.g. 
#7485 from cms-sw: Update tag for RecoTracker-FinalTrackSelectors to V01-03-00
this might explain why there are differences. 

Is there any cmssw PR to test to newly added file?

**Comment by mmusich** [comment]
> Is there any cmssw PR to test to newly added file?

Yes: https://github.com/cms-sw/cmssw/pull/36333

**Comment by mmusich** [comment]
@AdrianoDee, @srimanob
 
 Any objection on this one? It's necessary for cms-sw/cmssw#36333 to go in.
 Thanks

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- It just adds one file, needed by #36333

**Comment by perrotta** [comment]
merge

**Pull request merged**
